### ISSUE TITLE
Highlighted text

### ISSUE THREAD

**Issue by vs2961** [stuyspec/cms#39]
The cms needs a way to highlight text for articles, which doesn't exist at the moment.

**Comment by AndySok** [comment]
For devs: I think @dchen278 might have worked on this in the past. Ask him for more info!

**Comment by AndySok** [comment]
dchen actually coded this in before, so this issue is going to be open until he merges the change into the CMS

**Comment by dchen278** [comment]
Implemented in #55 

- Prosemirror schema changes
